#! /usr/bin/env bash
#
# Installs a new dev environment

sudo apt-get update \
  && sudo apt-get upgrade -yq \
  && sudo apt-get autoremove -yq

programs=(
  zsh 
  vim-gtk3 # allows for clipboard support
  stow 
  python3 
  tmux 
  gnome-tweak-tool
  curl
  ctags
)

for i in "${programs[@]}"; do 
  sudo apt-get install -yq "$i" 
done

if [[ $SHELL != $(which zsh) ]]; then
  echo "Changing shell to zsh"
  chsh -s "$(which zsh)"
fi

directories=(
  git
  vim
  zsh
  tmux
)

for i in "${directories[@]}"; do
  stow --dotfiles "$i"
done

ln -s "$PWD"/bin "$HOME"/bin

echo "Installation Complete!"
