#! /bin/bash
#
# Installs a new dev environment

sudo apt-get update -q \ 
  && sudo apt-get upgrade -yq \
  && sudo apt-get autoremove -yq

programs=(
  zsh 
  neovim 
  stow 
  python3 
  tmux 
  git 
  gnome-tweak-tool
  curl
)

for i in "${programs[@]}"; do 
	sudo apt-get install -yq $i 
done

if [ -d nord-gnome-terminal ]; then
  rm -rf "./nord-gnome-terminal"
fi
git clone https://github.com/arcticicestudio/nord-gnome-terminal.git \
  && ./nord-gnome-terminal/src/nord.sh \
  && rm -rf "./nord-gnome-terminal"

if [[ $SHELL != $(which zsh) ]]; then
	echo "Changing shell to zsh"
	chsh -s $(which zsh)
fi

directories=( 
  git 
  vim 
  nvim 
  zsh 
  tmux
)

for i in "${directories[@]}"; do
	stow --dotfiles $i
done

ln -s $PWD/bin $HOME/bin

cat << EOF
############################
# Installation Complete :) #
############################
EOF
