# URL: github.com/Griffin-Brome/dotfiles
# Authors: Griffin Brome
# Description: My tmux configuration


# remap prefix from 'C-b' to 'C-a'
unbind C-b
set-option -g prefix C-a
bind-key C-a send-prefix

#### key bindings ####

# reload config file
bind r source-file ~/.tmux.conf \; display ".tmux.conf reloaded!"

# split panes using | and -
bind | split-window -h
bind - split-window -v
unbind '"'
unbind %

# pane movement shortcuts (same as vim)
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

# don't rename windows automatically
set-option -g allow-rename off

# Enable mouse mode (tmux 2.1 and above)
set -g mouse on

# Lets use true color
# https://github.com/tmux/tmux/issues/1246
set -g default-terminal "tmux-256color"
set -ga terminal-overrides ",*256col*:Tc"

# theming
set -g status-style 'bg=colour8 fg=colour15'
set -g message-style 'bg=colour9 fg=colour0'
set -g pane-active-border-style 'fg=colour6'
set -g window-status-current-style 'bg=colour6 fg=colour8 bold'
set -g window-status-style 'bg=colour8 fg=colour6'

# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run -b '~/.tmux/plugins/tpm/tpm'
