" vim: fdm=marker
"        __
" __  __/\_\    ___ ___   _ __  ___
"/\ \/\ \/\ \ /' __` __`\/\`'_\/'___\
"\ \ \_/ \ \ \/\ \/\ \/\ \ \ \/\ \__/
" \ \___/ \ \_\ \_\ \_\ \_\ \_\ \____\
"  \/__/   \/_/\/_/\/_/\/_/\/_/\/____/
"
" Name: vimrc
" Author: Griffin Brome
" Description: My Vim config, feel free to copy :) Use :help <option> for any of these if you don't know what they do (or just google it)

" Plugin stuff {{{
" Install vim-plug if not found
if empty(glob('~/.vim/autoload/plug.vim'))
  silent !curl -fLo ~/.vim/autoload/plug.vim --create-dirs
    \ https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
endif

" Run PlugInstall if there are missing plugins
autocmd VimEnter * if len(filter(values(g:plugs), '!isdirectory(v:val.dir)'))
  \| PlugInstall --sync | source $MYVIMRC
\| endif
call plug#begin('~/.vim/plugged')
Plug 'arcticicestudio/nord-vim'
Plug 'vim-airline/vim-airline'
Plug 'tpope/vim-fugitive'
Plug 'scrooloose/nerdtree'
Plug 'ryanoasis/vim-devicons'
Plug 'christoomey/vim-tmux-navigator'
" Make sure you use single quotes
" Initialize plugin system
call plug#end()
"}}}

filetype plugin indent on

let mapleader = " " 

" https://github.com/rsaihe
nnoremap <silent> <C-l> :nohlsearch<CR><C-l> 

let g:airline_powerline_fonts = 1

nnoremap <leader>e :NERDTreeFocus<CR>
nnoremap <C-e> :NERDTreeToggle<CR>
" Exit Vim if NERDTree is the only window left.
autocmd BufEnter * if tabpagenr('$') == 1 && winnr('$') == 1 && exists('b:NERDTree') && b:NERDTree.isTabTree() |
    \ quit | endif

nnoremap Y y$


set termguicolors

colorscheme nord

set noswapfile
set smarttab
set hlsearch 
set incsearch 
set relativenumber
set number 
set laststatus=2 " Always show filename
set softtabstop=-1 " Use shiftwidth to determine tab size
set shiftwidth=2 " Indent by 2 spaces by default
set autoindent
set expandtab " Tabs instead of spaces
