" =============================================================================
" Name: vimrc
" Author: Griffin M. Brome (https://github.com/Griffin-Brome)
" Description: My vim config. 
" =============================================================================

" -----------------------------------------------------------------------------
" Basic
" -----------------------------------------------------------------------------
filetype plugin indent on
syntax on
set backspace=indent,eol,start
set hidden
set noswapfile

" Spaces instead of tabs
set expandtab

" -----------------------------------------------------------------------------
" Search
" -----------------------------------------------------------------------------
set hlsearch
set path=.,**
set wildignore+=*/node_modules/*,*/.git/*


" -----------------------------------------------------------------------------
" UI
" -----------------------------------------------------------------------------
set number relativenumber
set cursorline
set background=dark " TODO fix HACK: Fix colors in tmux

" Toggle project drawer
nnoremap <silent> <C-e> :25Lexplore <CR>
