" vim: fdm=marker
"        __
" __  __/\_\    ___ ___   _ __  ___
"/\ \/\ \/\ \ /' __` __`\/\`'_\/'___\
"\ \ \_/ \ \ \/\ \/\ \/\ \ \ \/\ \__/
" \ \___/ \ \_\ \_\ \_\ \_\ \_\ \____\
"  \/__/   \/_/\/_/\/_/\/_/\/_/\/____/
"
" Name: vimrc
" Author: Griffin Brome
" Description: My Vim config, feel free to copy :) Use :help <option> for any of these if you don't know what they do (or just google it)

" Plugin stuff {{{
" Install vim-plug if not found
if empty(glob('~/.vim/autoload/plug.vim'))
  silent !curl -fLo ~/.vim/autoload/plug.vim --create-dirs
    \ https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
endif

" Run PlugInstall if there are missing plugins
autocmd VimEnter * if len(filter(values(g:plugs), '!isdirectory(v:val.dir)'))
  \| PlugInstall --sync | source $MYVIMRC
\| endif
call plug#begin('~/.vim/plugged')
Plug 'arcticicestudio/nord-vim'
" Make sure you use single quotes
" Initialize plugin system
call plug#end()
"}}}

filetype plugin indent on

let mapleader = " " 

" Source: https://github.com/rsaihe
nnoremap <silent> <C-l> :nohlsearch<CR><C-l> 

nnoremap Y y$

set t_co=256

colorscheme nord

set noswapfile
set smarttab
set hlsearch 
set incsearch 
set relativenumber
set number 
set laststatus=2 " Always show filename
set softtabstop=-1 " Use shiftwidth to determine tab size
set shiftwidth=2 " Indent by 2 spaces by default
set autoindent
set expandtab " Tabs instead of spaces
