theme = "gruvbox"

[editor]
line-number = "relative"
mouse = false
end-of-line-diagnostics = "hint"

[editor.inline-diagnostics]
cursor-line = "warning" # show warnings and errors on the cursorline inline


[editor.indent-guides]
render = true

[editor.whitespace.render]
tab = "all"

[keys.normal]
# Holdovers from vim
"C-]" = "goto_definition"

# Better buffer movement
C-h = "jump_view_left"
C-j = "jump_view_down"
C-k = "jump_view_up"
C-l = "jump_view_right"

H = "goto_line_start"
L = "goto_line_end"

# https://yazi-rs.github.io/docs/tips#helix
C-y = [
	':sh rm -f /tmp/unique-ca1ea106',
	':insert-output yazi "%{buffer_name}" --chooser-file=/tmp/unique-ca1ea106',
	':sh printf "\x1b[?1049h\x1b[?2004h" > /dev/tty',
	':open %sh{cat /tmp/unique-ca1ea106}',
	':redraw',
	':set mouse false',
  ':set mouse true',
]

[keys.select]
H = "goto_line_start"
L = "goto_line_end"

