# remap prefix from 'C-b' to 'C-a'
unbind C-b
set-option -g prefix C-a
bind-key C-a send-prefix

# split panes using | and -
bind | split-window -h
bind - split-window -v
unbind '"'
unbind %

# always start counting at 1
set -g base-index 1

# https://github.com/tmux/tmux/issues/1246
set -g default-terminal "tmux-256color"
# https://deductivelabs.com/blog/tech/using-true-color-vim-tmux/
set -ga terminal-overrides ",xterm-256color:Tc"
